// <auto-generated />
using System;
using GSCS_Cameras_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GSCS_Cameras_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210509042308_Camera_mig")]
    partial class Camera_mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("GSCS_Cameras_API.Data.Camera", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ModelId");

                    b.HasIndex("SchoolID");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("GSCS_Cameras_API.Data.CameraModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CloseLensURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenLensURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaticImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("GSCS_Cameras_API.Data.School", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("GSCS_Cameras_API.Data.Camera", b =>
                {
                    b.HasOne("GSCS_Cameras_API.Data.CameraModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId");

                    b.HasOne("GSCS_Cameras_API.Data.School", "School")
                        .WithMany("Cameras")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("School");
                });

            modelBuilder.Entity("GSCS_Cameras_API.Data.School", b =>
                {
                    b.Navigation("Cameras");
                });
#pragma warning restore 612, 618
        }
    }
}
